version: '3.3'

volumes:
  pg_data:
  static:
  front_build:
  media:
  redoc:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: borisrow23/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/media
      - redoc:/app/api/docs/

  frontend:
    image: borisrow23/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /app/result_build/
    volumes:
      - front_build:/app/result_build/

  gateway:
    image: borisrow23/foodgram_nginx
    env_file: .env
    ports:
      - "8000:80"
    volumes:
      - static:/staticfiles/
      - media:/media
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend