version: '3.3'

volumes:
  pg_data:
  static:
  front_build:
  media:
  redoc:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: borisrow23/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/media

  frontend:
    image: borisrow23/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - /frontend/:/app/result_build
      - static:/frontend_static

  nginx:
    image: borisrow23/foodgram_nginx
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/staticfiles/
      - media:/media
      - ./frontend/build:/usr/share/nginx/html/
      - redoc:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend