# Generated by Django 3.2.3 on 2024-03-07 10:05

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20240307_1252'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='name_measurement_unit',
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(condition=models.Q(('measurement_unit', django.db.models.expressions.F('measurement_unit')), ('name', django.db.models.expressions.F('name'))), fields=('name', 'measurement_unit'), name='unique_ingredient_fields'),
        ),
    ]
